apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: cheiiau/solid-app-client:version1.0
      ports:
        - containerPort: 3000