version: '3.9'
services:
  nginx:
    mem_limit: 128m
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    mem_limit: 64m
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    mem_limit: 64m
    build:
      dockerfile: Dockerfile
      context: ./client